### ISSUE TITLE
Consider not overwriting the Object#send method.

### ISSUE THREAD

**Issue by tsnow** [hipchat/hipchat-rb#45]
https://github.com/hipchat/hipchat-rb/blob/master/lib/hipchat.rb#L76
https://github.com/hipchat/hipchat-rb/blob/master/lib/hipchat/capistrano.rb#L54

This isn't technically a bug, as hipchat-rb works great, but you might consider not overwriting http://ruby-doc.org/core-2.0.0/Object.html#method-i-send in HipChat::Room and in the capistrano recipe.

Here's a failing test, if that helps:

``` bash
gems/hipchat-0.10.0> cat spec/new_spec.rb 
```
```ruby
require File.expand_path(File.dirname(__FILE__) + '/spec_helper')
describe HipChat do
  subject { HipChat::Client.new('blah') }
  
  let(:room) { subject['Hipchat'] }
  it 'doesnt overwrite ruby core methods' do
    #$stderr.puts(:hi, room.send(:inspect));
    room.__send__(:inspect).should == room.send(:inspect)
  end
end
```
```bash
gems/hipchat-0.10.0> rspec spec/new_spec.rb 
F

Failures:

  1) HipChat doesnt overwrite ruby core methods
     Failure/Error: room.__send__(:inspect).should == room.send(:inspect)
     ArgumentError:
       wrong number of arguments (1 for 2)
     # ./lib/hipchat.rb:63:in `send'
     # ./spec/new_spec.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.00043 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/new_spec.rb:6 # HipChat doesnt overwrite ruby core methods
```

**Comment by backus** [comment]
+1
